### ISSUE TITLE
Issue with the "clear" command not working

### ISSUE THREAD

**Issue by rayane-mallek** [tristan-gaido/tp-git#2]
Hello,

I hope this message finds you well. I am writing to report an issue with the "clear" command not working correctly on my system. I have tried using the command multiple times, but it does not clear the terminal screen as expected (it always add an "a" character).

I am running the command on a Unix-based system, and I have checked that the command is available and executable. However, it still does not work.

Could you please help me resolve this issue? I rely on the "clear" command for my work, and it is hindering my productivity. If you need any additional information, please let me know.

Thank you for your time and attention to this matter.

Best regards,
Rayane

**Comment by tristan-gaido** [comment]
pas lu

**Comment by tristan-gaido** [comment]
mais bon c'est corrigé
